### PR TITLE
JENKINS-30146 Plugin is hanging builds when running concurrently

### PR DESCRIPTION
**Pull request by lsbwant**
I am not sure this fixed is good, but I have tested, it has worked.
Signed-off-by: Shuaibing Li <Shuaibing.Li@lombardrisk.com>

### CODE REVIEW

**Comment by deruyter** [comment]
Ok I'll check this
Regards

Thomas


2016-01-18 6:49 GMT+01:00 lsbwant <notifications@github.com>:

> I am not sure this fixed is good, but I have tested, it has worked.
> Signed-off-by: Shuaibing Li Shuaibing.Li@lombardrisk.com
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/jenkinsci/summary_report-plugin/pull/4
> Commit Summary
>
>    - JENKINS-30146 Plugin is hanging builds when running concurrently
>
> File Changes
>
>    - *M*
>    src/main/java/hudson/plugins/summary_report/ACIPluginProjectAction.java
>    <https://github.com/jenkinsci/summary_report-plugin/pull/4/files#diff-0>
>    (2)
>    - *M*
>    src/main/java/hudson/plugins/summary_report/ACIPluginPublisher.java
>    <https://github.com/jenkinsci/summary_report-plugin/pull/4/files#diff-1>
>    (2)
>
> Patch Links:
>
>    - https://github.com/jenkinsci/summary_report-plugin/pull/4.patch
>    - https://github.com/jenkinsci/summary_report-plugin/pull/4.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jenkinsci/summary_report-plugin/pull/4>.
>



-- 

Thomas Deruyter

Tel: +33 (0)6 64 86 95 00

tderuyte@gmail.com

**Comment by gabrielpreston** [comment]
@deruyter Have you had a chance to look at this and give it a test? This has been an ongoing issue in our Jenkins environment and we'd love to see this patch make it in.

**Comment by deruyter** [comment]
Yes. I plan to do it this week
Regards
Le 27 janv. 2016 12:45 AM, "Gabriel Preston" <notifications@github.com> a
écrit :

**Comment by gabrielpreston** [comment]
Great news, thanks!

**Pull request merged**
